// this type was generated by AutoImplement
using System.Delegation;

namespace AutoImplementTests
{
    public class StubHasCustomEvent :  IHasCustomEvent
    {
        public EventImplementation<int> CustomEvent = new EventImplementation<int>();
        
        event CustomEventHandler IHasCustomEvent.CustomEvent
        {
            add
            {
                CustomEvent.add(new System.EventHandler<int>(value));
            }
            remove
            {
                CustomEvent.remove(new System.EventHandler<int>(value));
            }
        }
    }
}
